site_name: Video Conferencing with Zoom Documentation
repo_url: https://github.com/techies23/video-conference-zoom
site_author: Deepen Bajracharya
copyright: Deepen Bajracharya (CodeManas)
nav:
  - Getting Started: index.md
  - Installation:
      - API Keys Integration: integration.md
      - OAuth Connection: oauth.md
      - Uninstalling App: uninstalling.md
  - Usage:
      - Meeting Types: meeting_types.md
      - Webinars: webinars.md
      - Shortcode: shortcode.md
      - Change DateTime: date_types.md
      - Join via Browser: join_links.md
      - Vanity URL: vanity_url.md
      - Template Override: template_override.md
      - Filter Hooks: filters_hooks.md
      - Import Meeting: import-meetings.md
      - Assign Host Page: assign_host.md
  - Addons:
    - Video Conferencing with Zoom Pro: vczapi-pro.md
    - WooCommerce (Addon): woocommerce.md
    - WooCommerce Product Vendors (Addon): woocommerce-product-vendors.md
    - WooCommerce Bookings (Addon): woocommerce-booking.md
    - Booked Appointments (Addon): booked-appointments.md
    - WCFM (Addon): wcfm.md
    - WooCommerce Appointments (addon): woocommerce-appointments.md
  - FAQ: faq.md
  - Support: support.md
theme:
  name: material